name: Deploy Astro Portfolio to GitHub Pages

on: 
  workflow_dispatch: {}
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Install Astro GitHub Adapter
      #   run: npm install @astrojs/github

      # - name: Patch astro.config.mjs for GitHub Pages
      #   run: |
      #     echo "🔧 Patching astro.config.mjs..."
      #     echo 'import { defineConfig } from "astro/config";' > astro.config.mjs
      #     echo 'import github from "@astrojs/github";' >> astro.config.mjs
      #     echo '' >> astro.config.mjs
      #     echo 'export default defineConfig({' >> astro.config.mjs
      #     echo '  output: "static",' >> astro.config.mjs
      #     echo '  adapter: github(),' >> astro.config.mjs
      #     echo '});' >> astro.config.mjs

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
